name: lint and test

on: [push]

jobs:
  setup_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

    outputs:
      gem_cache_path: ${{ steps.setup-ruby.outputs.bundler-cache-path }}

  rubocop:
    runs-on: ubuntu-latest
    name: Run RuboCop
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby for RuboCop
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop -D --parallel

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.3", "3.4"]
    name: Ruby ${{ matrix.ruby }} Tests
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: sql_lint_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec tests
        env:
          DATABASE_URL: "postgres://postgres:password@localhost:5432/sql_lint_test"
        run: bundle exec rspec

  yard:
    runs-on: ubuntu-latest
    name: Check YARD Documentation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby for YARD
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Generate YARD Docs and Check Warnings
        run: bundle exec yard doc --fail-on-warning --no-output
